### ISSUE TITLE
Time of start = ? 

### ISSUE THREAD

**Issue by jcolomb** [jcolomb/HCS_analysis#1]
Is there a way to read the exact time when the experiment was started from the HCS output data?

**Comment by vkobla** [comment]
Hi Julien,
This is Vikrant Kobla at Clever Sys. I'm the person who designed the HomeCageScan system from the start and can help you with most questions. 

OK, for this question, since a real-time video analysis is assumed for such recording, that Video-Start-Time information is only saved in the Experiment Database to which that trial/video/recording was logged into. As a standalone video file, we don't have the meta-data saved in the file.

Saving the time of recording needs to be assigned to the video itself. Because, the video can be analyzed any number of times subsequently, each analysis can yield a different set of results (if the companion inputs are different), we didn't find it appropriate to save this information in the result file.

What do you think about this reasoning?  Any suggestions or comments welcome.

**Comment by jcolomb** [comment]
Having the time of start in the video name is valuable. This works unfortunately only when people kept the video files, though.

You might think about a way to create a metadata file independent on the results file (or as a standalone sheet in the result file), in order to have this kind of information computer readable.
