### ISSUE TITLE
SVM analysis expected time/failure

### ISSUE THREAD

**Issue by mikerspencer** [jcolomb/HCS_analysis#34]
Does this sometimes fail on the supplied test data? If so, I would remove it.

I tried it (on an i5 9500), but killed the process after 4 hours without a result.

**Comment by jcolomb** [comment]
It does technically work on my machine (I am still not confident with the code itself since the results are strange).

Did you make more than one permutation? I does take quite some time (on my system with one permutation: about 6 minutes).

I have no linux machine to see whether it is a linux problem, no success with shinyapps.io, probably the folder tree is not correct for it to work there.

**Comment by jcolomb** [comment]
@mikerspencer thank you again for your reviews, did you try a unique permutation ? Is it still failing and if yes, do you have any advice on how I could engage with linux-specific problem ?
